using System.ComponentModel;
using System.Globalization;
using System.Reflection;
using System.Resources;

namespace Setrz.Mobile.Shared.Services;

public class LocalizationResourceManager
{
    private static readonly Lazy<LocalizationResourceManager> _instance = 
        new Lazy<LocalizationResourceManager>(() => new LocalizationResourceManager());

    public static LocalizationResourceManager Instance => _instance.Value;

    // The ResourceManager generated by the AppResources.resx file
    private readonly ResourceManager _resourceManager;

    private LocalizationResourceManager()
    {
        // Get the ResourceManager for the AppResources.resx file
        var assembly = typeof(LocalizationResourceManager).GetTypeInfo().Assembly;
        _resourceManager = new ResourceManager("Setrz.Mobile.Resources.AppResources", assembly);
    }

    // Indexer property to access strings easily in C#
    public string this[string text]
    {
        get
        {
            // Retrieve the localized string using the current culture
            string localizedText = _resourceManager.GetString(text, CultureInfo.CurrentCulture);
            
            // Return the key if the string is not found (for easy debugging)
            return localizedText ?? text;
        }
    }

    public void SetCulture(CultureInfo culture)
    {
        // Set the current culture for the application
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        
        // Notify the UI that all bound resource strings need to be re-evaluated
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
    }

    public event PropertyChangedEventHandler PropertyChanged;
}